/**
 * routes.tsx — Centralised route table.
 *
 * OWNERSHIP: Person A exclusively. If work on Person B or C's pages seems
 * to require a new route, flag it — do not edit this file directly.
 *
 * Phase A routes only. No sync/Phase B routes here yet.
 */

import { createBrowserRouter, Navigate } from 'react-router-dom'
import AppLayout from './layout/AppLayout'
import LoginPage       from './pages/Login/LoginPage'
import DashboardPage   from './pages/Dashboard/DashboardPage'
import PatientListPage from './pages/PatientList/PatientListPage'
import PatientFormPage from './pages/PatientForm/PatientFormPage'

export const router = createBrowserRouter([
  {
    // Unauthenticated routes (no layout shell)
    path: '/login',
    element: <LoginPage />,
  },
  {
    // Authenticated shell — wraps all in-app pages
    element: <AppLayout />,
    children: [
      {
        index: true,
        // Redirect bare "/" to dashboard
        element: <Navigate to="/dashboard" replace />,
      },
      {
        path: 'dashboard',
        element: <DashboardPage />,
      },
      {
        path: 'patients',
        element: <PatientListPage />,
      },
      {
        path: 'patients/new',
        element: <PatientFormPage />,
      },
      {
        path: 'patients/:id/edit',
        element: <PatientFormPage />,
      },
    ],
  },
])
